# Generated by Django 4.2.7 on 2025-11-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen adjunta al ticket', null=True, upload_to='ticket_images/'),
        ),
    ]
